../../example/src/wasm4nia_theme.h: ./wasm4nia_theme.mid ./wasm4nia_theme.json ../convert.js
	../midi2c.sh wasm4nia_theme ./wasm4nia_theme.mid ./wasm4nia_theme.json $@

.PHONY: clean
clean:
	rm -f ../../example/src/wasm4nia_theme.h